apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xp4oirhpi-go 
  janus-idp.io/tekton: xp4oirhpi-go
  backstage.io/kubernetes-id: xp4oirhpi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xp4oirhpi-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml